feat: update readme and description
SysBioChalmers/sybil-clpAPI pull request #1
Opened 2022-08-11 06:56 UTC by mihai-sysbio

This PR is mainly focused on the usability of the repository, updating the description and the `README.md`.

2022-08-11 13:01 UTC, mro100 requested changes
Only found a cplexAPI in the newly inserted text in README.md, that should read "clpAPI".

2022-08-11 13:01 UTC, mro100 commented on README.md
> +_Note_: This repository was previously hosted at https://gitlab.cs.uni-duesseldorf.de/general/ccb/cplexAPI.
This should read clpAPI in the end.

2022-08-11 13:04 UTC, mihai-sysbio commented on README.md
> +_Note_: This repository was previously hosted at https://gitlab.cs.uni-duesseldorf.de/general/ccb/cplexAPI.
Oh sorry about that, there was a lot of copy-pasting involved ☺️ 

```suggestion
_Note_: This repository was previously hosted at https://gitlab.cs.uni-duesseldorf.de/general/ccb/clpAPI.
```

2022-08-17 12:25 UTC, mro100 approved these changes

2022-08-17 12:26 UTC, merged